# Site
title:              Estela Diaz
bio:                'Web Developer, Biologist, Professional Extrovert'
description:        "A person of many interests."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/galaxy.jpg'
tiled_bg:           false
locale:             en_US
#url:              diazela.com
url:                https://esteladiaz.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
email: estela@diazela.com
twitter:            _diazela
facebook:           diazela
github:             esteladiaz
linkedin:           diazestela
#instagram:          diazela

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://twitter.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
